{% set version = "2.0a" %}

package:
  name: menuinst
  version: {{ version }}

source:
  git_url: https://github.com/jaimergp/menuinst
  git_rev: cep

build:
  number: 10
  string: "{{ PKG_BUILDNUM }}_{{ GIT_DESCRIBE_HASH }}_h{{ PKG_HASH }}"
  script:
    - {{ PYTHON }} -m pip install . -vv
    # - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"  # [win]
  # entry_points:
  #   - menuinst = menuinst.main:main
  # skip_compile_pyc:
  #   - cwp.py

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pydantic
    - typing_extensions  # [py<=37]
    - pywin32  # [win]

test:
  imports:
    - menuinst

  # commands:
  #   - menuinst --help

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items

  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - jaimergp
