{% set version = "2.0a" %}

package:
  name: menuinst
  version: {{ version }}

source:
  git_url: https://github.com/jaimergp/menuinst
  git_rev: cep

build:
  number: 36
  string: "{{ PKG_BUILDNUM }}_{{ GIT_DESCRIBE_HASH }}_h{{ PKG_HASH }}"
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
    # - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"  # [win]
  # entry_points:
  #   - menuinst = menuinst.main:main
  # skip_compile_pyc:
  #   - cwp.py

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - conda
    - pytest 
    - pytest-cov 
    - pydantic 
    - hypothesis 
    - hypothesis-jsonschema
  source_files:
    - tests
  imports:
    - menuinst
  commands:
    - pytest --no-cov -vvs

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items

  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - jaimergp
