{% set version = "2.0a" %}

package:
  name: menuinst
  version: {{ version }}

source:
  git_url: https://github.com/conda/menuinst
  git_rev: cep-devel

build:
  number: 50
  string: "py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ GIT_DESCRIBE_HASH }}_{{ PKG_BUILDNUM }}"
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    # Apparently these files make the post-build linkage analysis crash
    # and we should not need them on Windows
    - del /q "{{ SRC_DIR }}\\menuinst\\data\\osx_launcher_*"  # [win]
    - {{ PYTHON }} -m pip install . -vv
  # entry_points:
  #   - menuinst = menuinst.main:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - conda
    - pytest
    - pytest-cov
    - pydantic
    - hypothesis
    - hypothesis-jsonschema
  source_files:
    - tests
  imports:
    - menuinst
  commands:
    - pytest --no-cov -vvs

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items

  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - jaimergp
